version: '3.7'
services:
  postgres:
      image: postgres:10.5
      restart: unless_stopped
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5438:5432'
      volumes:
        #- ./api/db/postgres-test-data:/var/lib/postgresql/data
        - /postgres/scribemonster:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: unless_stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local