#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
- name: scribe.monster-web
  type: web
  env: static
  buildCommand: yarn install && yarn rw deploy render web
  staticPublishPath: ./web/dist
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: SKIP_INSTALL_DEPS
    value: true
  routes:
  - type: rewrite
    source: /.redwood/functions/*
#####
# NOTE: replace destination api url after first deploy to Render
# example:
#   destination: https://myredwoodproject-api.onrender.com/*
#####
    destination: https://scribe-monster-api.onrender.com/*
  - type: rewrite
    source: /undefined/*
    destination: https://scribe-monster-api.onrender.com/auth
    # this is an issue that needs to be fixed
  - type: rewrite
    source: /*
    destination: /index.html
  headers:
  - path: /*
    name: X-Frame-Options
    value: DENY
  - path: /*
    name: X-XSS-Protection
    value: "1; mode=block"
  - path: /*
    name: X-Content-Type-Options
    value: "nosniff"
  - path: /*
    name: Strict-Transport-Security
    value: "max-age=63072000; includeSubDomains; preload"
  - path: /*
    name: Referrer-Policy
    value: "same-origin"
    #Content-Security-Policy = "default-src 'none'; manifest-src 'self'; worker-src 'self'; connect-src 'self'                                        ; img-src 'self'; script-src 'self'                                           ; style-src 'self' 'unsafe-inline'; frame-ancestors 'self'; base-uri 'self';"
  - path: /*
    name: Content-Security-Policy
    value: "default-src 'none'; manifest-src 'self'; worker-src 'self'; connect-src 'self' https://monitoring.jace.pro/api/collect; img-src 'self'; script-src 'self' https://monitoring.jace.pro/minneapolis.js 'unsafe-inline'; style-src 'unsafe-inline'       ; frame-ancestors 'self'; base-uri 'self'; frame-src youtube.com www.youtube.com;"

- name: scribe.monster-api
  type: web
  env: node
  region: oregon
  buildCommand: yarn && yarn rw build api
  startCommand: yarn rw deploy render api
  envVars:
  - key: NODE_VERSION
    value: 16
  - key: DATABASE_URL
    fromDatabase:
      name: scribe.monster-db
      property: connectionString
- type: redis
  name: scribe.monster-cache
  #ipAllowList: [] # only allow internal connections
  plan: free # optional (defaults to starter)
  maxmemoryPolicy: allkeys-lfu # optional (defaults to allkeys-lru). Rails recommends allkeys-lfu as a default.
  ipAllowList:
  - source: 0.0.0.0/0
    description: public

databases:
  - name: scribe.monster-db
    region: oregon

